language: java
dist: trusty

before_install:
  - rm -rf $HOME/.m2/repository/io/vlingo
  - cp .travis/settings.xml $HOME/.m2/settings.xml
  # Force caching of maven plugins used during deploy phase
  - mvn deploy:help versions:help help:help

script:
  - mvn install

before_cache:
  - rm -rf $HOME/.m2/repository/io/vlingo
cache:
  directories:
    - $HOME/.m2/repository

deploy:
  - provider: script
    script: "mvn deploy -DskipTests"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: "mvn deploy -DskipTests"
    skip_cleanup: true
    on:
      branch: master

notifications:
  slack:
    secure: dOFTUTixPWoLwDkD8rTzgBVqptakuZVbD6LRbk4yCMd+NaU8qgshnG3X/LDqM1iU1F0Ve7AnSkJrlTakMtw+25dHpaddZD3qP+AsPrI0HQaj3yyljAQ4mN/eZpKYRkgyY7x6Jy65piOdUFxwiZ8CEVCByBskjzNqEN9iXR1v5o9eRos0Ms4mNCLOv+mnHv80LhYVqj4i29Eud8mHfNq8I1iwGmJSTeAB1VNt+DFngtItpzGeXu6VkCdxG16ofTI0zuGWneJtjH4tG8MCszX2jT/bpSGim4rrU98sZZZTF5ngJTAPR+Aelb+SWcxLidBnoTo0sYWUqGTet2Wu0lJ9xJq8iUO8xon2ePfWjGDaZedNj6fslVFr5e+Uf8wdD3KSXPWUedIbUdODus4r6EAF85loImwOrmUX6V3yu5YiSXwZ6+2BBI0vdIQLkSJsoPUyegFxY97RWl+soQsD6X9GJFSHR9UeKA4M3uTIDfIsqxYyGvcCvqlkfEfyFfZGLbkBeXXvpPtS4PZfc0mdsd2vrnBRvKuC5XJVeaQpR+bjbmcaPA9cgxDcMm/qZqO4l3c/AvY240lfId2+mlEmX1E7pbI5zcg1GcN7a4VpmG24wKCG9LpkZvDTqhAJYQ/j8PPghs1kHkXGn9OdntEWUbc5Qxr/RCdBKs7ttCV9iGL78Tc=
